<?php
/**
 * Implements hook_views_api().
 */
function d7vrpv_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'd7vrpv'),
  );
}
/**
 * Implements hook_views_default_views().
 */
function d7vrpv_views_default_views() {
  return d7vrpv_list_all_nodes();
}
/**
 * Begin view
 */
function d7vrpv_list_all_nodes() {
  /*
   * View 'list_all_nodes'
   */
  $view =   views_new_view();
  $view->name = 'list_all_nodes';
  $view->description = 'Provide a list of node titles, 
    creation dates, owner and status';
  $view->tag = '';
  $view->view_php = '';
  $view->base_table = 'node';
  $view->is_cacheable = FALSE;
  $view->api_version = '3.0-alpha1';
  $view->disabled = FALSE; /* Edit this to true to make a 
    default view disabled initially */
  
//   var_dump($view);
//   exit();
  
/* Display: Defaults */
  $handler = $view->new_display('default', 'Defaults', 'default');
  $handler->display->display_options['title'] = 'List All Nodes';
  $handler->display->display_options['access']['type'] = 'role';
  $handler->display->display_options['access']['role'] = array(
    '3' => '3',
  );  
  $handler->display->display_options['cache']['type'] = 'none';
$handler->display->display_options['exposed_form']['type'] = 
    'basic';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->
    display_options['pager']['options']['items_per_page'] = '15';
  $handler->display->display_options['pager']['options']
    ['offset'] = '0';
  $handler->display->display_options['pager']['options']
    ['id'] = '0';
  $handler->display->display_options['style_plugin'] = 'table';
  $handler->display->display_options['style_options']
    ['columns'] = array(
     'title' => 'title',
     'type' => 'type',
     'created' => 'created',
     'name' => 'name',
     'status' => 'status',
  );
  $handler->display->display_options['style_options']
    ['default'] = 'created';
  $handler->display->display_options['style_options']
    ['info'] = array(
     'title' => array(
       'sortable' => 1,
       'align' => 'views-align-left',
       'separator' => '',
     ),
     'type' => array(
       'sortable' => 1,
       'align' => 'views-align-left',
       'separator' => '',
     ),
     'created' => array(
       'sortable' => 1,
       'align' => 'views-align-left',
       'separator' => '',
     ),
 'name' => array(
       'sortable' => 1,
       'align' => 'views-align-left',
       'separator' => '',
     ),
     'status' => array(
       'sortable' => 1,
       'align' => 'views-align-left',

       'separator' => '',
     ), 
  );
  $handler->display->display_options['style_options']
    ['override'] = 1;
  $handler->display->display_options['style_options']
    ['sticky'] = 0;
  $handler->display->display_options['style_options']
    ['order'] = 'desc';
  /* Header: Global: Text area */
  $handler->display->display_options['header']['area']
    ['id'] = 'area';
  $handler->display->display_options['header']['area']
    ['table'] = 'views';
  $handler->display->display_options['header']['area']
    ['field'] = 'area';
  $handler->display->display_options['header']['area']
    ['empty'] = TRUE;
  $handler->display->display_options['header']['area']
    ['content'] = '<h2>Following is a list of all non-page 
     nodes.</h2>';
  $handler->display->display_options['header']['area']
    ['format'] = '3';
  /* Footer: Global: Text area */
  $handler->display->display_options['footer']['area']
    ['id'] = 'area';
  $handler->display->display_options['footer']['area']
    ['table'] = 'views';
  $handler->display->display_options['footer']['area']
    ['field'] = 'area';
  $handler->display->display_options['footer']['area']
    ['empty'] = TRUE;
  $handler->display->display_options['footer']['area']
    ['content'] = '<small>This view is brought to you courtesy 
      of the D7 Views Recipes module</small>';
  $handler->display->display_options['footer']['area']
    ['format'] = '3';
  /* Field: Node: Title */
  $handler->display->display_options['fields']['title']
    ['id'] = 'title';
  $handler->display->display_options['fields']['title']
    ['table'] = 'node';
  $handler->display->display_options['fields']['title']
    ['field'] = 'title';
  $handler->display->
    display_options['fields']['title']['alter']['alter_text'] = 0;
$handler->display->
    display_options['fields']['title']['alter']['make_link'] = 0;
  $handler->display->
    display_options['fields']['title']['alter']['trim'] = 0;
  $handler->display->
    display_options['fields']['title']['alter']
     ['word_boundary'] = 1;
  $handler->display->
    display_options['fields']['title']['alter']['ellipsis'] = 1;
  $handler->display->
    display_options['fields']['title']['alter']['strip_tags'] = 0;
  $handler->display->
    display_options['fields']['title']['alter']['html'] = 0;
  $handler->display->
    display_options['fields']['title']['hide_empty'] = 0;
  $handler->display->
    display_options['fields']['title']['empty_zero'] = 0;
  $handler->display->
    display_options['fields']['title']['link_to_node'] = 0;
  /* Field: Node: Type */
  $handler->display->display_options['fields']['type']
    ['id'] = 'type';
  $handler->display->display_options['fields']['type']
    ['table'] = 'node';
  $handler->display->display_options['fields']['type']
    ['field'] = 'type';
$handler->display->
    display_options['fields']['type']['alter']['alter_text'] = 0;
  $handler->display->
    display_options['fields']['type']['alter']['make_link'] = 0;
  $handler->display->
    display_options['fields']['type']['alter']['trim'] = 0;
  $handler->display->
    display_options['fields']['type']['alter']
      ['word_boundary'] = 1;
  $handler->display->
    display_options['fields']['type']['alter']['ellipsis'] = 1;
  $handler->display->
    display_options['fields']['type']['alter']['strip_tags'] = 0;
  $handler->display->
    display_options['fields']['type']['alter']['html'] = 0;
  $handler->display->
    display_options['fields']['type']['hide_empty'] = 0;
  $handler->display->
    display_options['fields']['type']['empty_zero'] = 0;
  $handler->display->
    display_options['fields']['type']['link_to_node'] = 0;
$handler->display->
    display_options['fields']['type']['machine_name'] = 0;
  /* Field: Node: Post date */
  $handler->display->display_options['fields']['created']
    ['id'] = 'created';
  $handler->display->display_options['fields']['created']
    ['table'] = 'node';
  $handler->display->display_options['fields']['created']
    ['field'] = 'created';
  $handler->display->
    display_options['fields']['created']['alter']
      ['alter_text'] = 0;
  $handler->display->
    display_options['fields']['created']['alter']
      ['make_link'] = 0;
  $handler->display->
    display_options['fields']['created']['alter']['trim'] = 0;
  $handler->display->
    display_options['fields']['created']['alter']
      ['word_boundary'] = 1;
  $handler->display->
    display_options['fields']['created']['alter']['ellipsis'] = 1;
  $handler->display->
    display_options['fields']['created']['alter']
      ['strip_tags'] = 0;
  $handler->display->
    display_options['fields']['created']['alter']['html'] = 0;
  $handler->display->
    display_options['fields']['created']['hide_empty'] = 0;
  $handler->display->
    display_options['fields']['created']['empty_zero'] = 0;
  $handler->display->
    display_options['fields']['created']['date_format'] = 
      'custom';
  $handler->display->
    display_options['fields']['created']['custom_date_format'] = 
      'Y-m-d';
  /* Field: User: Name */
  $handler->display->display_options['fields']['name']
    ['id'] = 'name';
  $handler->display->display_options['fields']['name']
    ['table'] = 'users';
  $handler->display->display_options['fields']['name']
    ['field'] = 'name';
  $handler->display->display_options['fields']['name']
    ['label'] = 'Author';
$handler->display->
    display_options['fields']['name']['alter']['alter_text'] = 0;
  $handler->display->
    display_options['fields']['name']['alter']['make_link'] = 0;
  $handler->display->
    display_options['fields']['name']['alter']['trim'] = 0;
  $handler->display->
    display_options['fields']['name']['alter']
      ['word_boundary'] = 1;
  $handler->display->
    display_options['fields']['name']['alter']['ellipsis'] = 1;
  $handler->display->
    display_options['fields']['name']['alter']['strip_tags'] = 0;
  $handler->display->
    display_options['fields']['name']['alter']['html'] = 0;
  $handler->display->
    display_options['fields']['name']['hide_empty'] = 0;
  $handler->display->
    display_options['fields']['name']['empty_zero'] = 0;
  $handler->display->
    display_options['fields']['name']['link_to_user'] = 0;
  $handler->display->
    display_options['fields']['name']['overwrite_anonymous'] = 0;
  /* Field: Node: Published */
  $handler->display->display_options['fields']['status']
    ['id'] = 'status';
  $handler->display->display_options['fields']['status']
    ['table'] = 'node';
  $handler->display->display_options['fields']['status']
    ['field'] = 'status';
  $handler->display->
    display_options['fields']['status']['alter']
    ['alter_text'] = 0;
  $handler->display->
    display_options['fields']['status']['alter']['make_link'] = 0;
  $handler->display->
 display_options['fields']['status']['alter']['trim'] = 0;
  $handler->display->
    display_options['fields']['status']['alter']
      ['word_boundary'] = 1;
  $handler->display->
    display_options['fields']['status']['alter']['ellipsis'] = 1;
  $handler->display->
    display_options['fields']['status']['alter']
      ['strip_tags'] = 0;
  $handler->display->
    display_options['fields']['status']['alter']['html'] = 0;
 $handler->display->
    display_options['fields']['status']['hide_empty'] = 0;
  $handler->display->
    display_options['fields']['status']['empty_zero'] = 0;
  $handler->display->display_options['fields']['status']
    ['type'] = 'true-false';
  $handler->display->display_options['fields']['status']
    ['not'] = 0;
  /* Sort criterion: Node: Post date */
  $handler->display->display_options['sorts']['created']
    ['id'] = 'created';
  $handler->display->display_options['sorts']['created']
    ['table'] = 'node';
  $handler->display->display_options['sorts']['created']
    ['field'] = 'created';
  $handler->display->display_options['sorts']['created']
    ['order'] = 'DESC';
  /* Filter: Node: Type */
  $handler->display->display_options['filters']['type']
    ['id'] = 'type';
  $handler->display->display_options['filters']['type']
    ['table'] = 'node';
  $handler->display->display_options['filters']['type']
    ['field'] = 'type';
  $handler->display->
    display_options['filters']['type']['operator'] = 'not in';
  $handler->display->display_options['filters']['type']
    ['value'] = array(
      'page' => 'page',
    );
/* Display: Page */
  $handler = $view->new_display('page', 'Page', 'page_1');
  $handler->display->display_options['path'] = 'list-all-nodes';
  $views[$view->name] = $view;
  return $views;
}
?>