<?php

/**
 * Implements hook_menu().
 */
function cruiseimages_menu() {

    //Gift Card Table List View
    $items['cruiseimages'] = array(
        'title' => 'Gift Card',
        'page callback' => 'cruiseimages_list_view',
        'access arguments' => array('view cruiseimages entity'),
    );

    //Adding New Card
    $items['cruiseimages/add'] = array(
        'title' => 'Add Gift Card',
        'page callback' => 'cruiseimages_add',
        'access arguments' => array('create cruiseimages entities'),
        'file' => 'cruiseimages.form.inc',
    );

    //Edit Gift Card
    $items['cruiseimages/%cruiseimages/edit'] = array(
        'title' => 'Edit',
        'load arguments' => array('cruiseimages'),
        'type' => MENU_LOCAL_TASK,
        'page callback' => 'cruiseimages_item_edit',
        'access arguments' => array('edit cruiseimages entities'),
        'page arguments' => array(1),
        'file' => 'cruiseimages.form.inc',
    );

    //Delete Gift Card
    $items['cruiseimages/%/delete'] = array(
        'page callback' => 'cruiseimages_item_delete',
        'access arguments' => array('delete cruiseimages entities'),
        'page arguments' => array(1),
        'file' => 'cruiseimages.form.inc',
    );

    //Manage Gift Card through Admin Panel
    $items['admin/structure/cruiseimages/manage'] = array(
        'title' => 'Gift Card',
        'description' => 'Manage Gift Card',
        'page callback' => 'cruiseimages_admin_page',
        'access arguments' => array('administer Request Quote entities'),
    );
    return $items;
}

/**
 * Implements hook_permission().
 */
function cruiseimages_permission() {
    return array(
        'administer cruiseimages entities' => array(
            'title' => t('Administer cruiseimages entities'),
            'restrict access' => TRUE,
        ),
        'view cruiseimages entities' => array(
            'title' => t('View cruiseimages Entities'),
        ),
        'create cruiseimages entities' => array(
            'title' => t('Create cruiseimages Entities'),
        ),
        'delete cruiseimages entities' => array(
            'title' => t('Delete cruiseimages Entities'),
        ),
    );
}

/**
 * Implements hook_entity_info().
 */
function cruiseimages_entity_info() {
    $cruiseimages_info['cruiseimages'] = array(
        'label' => 'cruiseimages',
        'controller class' => 'cruiseimagesController',
        'base table' => 'cruiseimages',
        'uri callback' => 'cruiseimages_uri',
        'fieldable' => TRUE,
        'entity keys' => array(
            'id' => 'id',
        ),
        'static cache' => TRUE,
        'bundles' => array(
            'cruiseimages_bundle' => array(
                'label' => 'cruiseimages',
                'admin' => array(
                    'path' => 'admin/structure/cruiseimages/manage',
                    'access arguments' => array('administer cruiseimages entities'),
                ),
            ),
        ),
        'view modes' => array(
            'full' => array(
                'label' => t('Full'),
                'custom settings' => FALSE,
            ),
        )
    );
    return $cruiseimages_info;
}

function cruiseimages_page_title($cruiseimages) {
    return 'Gift Card';
}

function cruiseimages_load($id = NULL, $reset = FALSE) {
    $ids = (isset($id) ? array($id) : array());
    $cruiseimages = cruiseimages_load_multiple($ids, array(), $reset);
    return $cruiseimages ? reset($cruiseimages) : FALSE;
}

function cruiseimages_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
    return entity_load('cruiseimages', $ids, $conditions, $reset);
}

function cruiseimages_uri($cruiseimages) {
    return array(
        'path' => 'cruiseimages/' . $cruiseimages->id,
    );
}

function cruiseimages_item_delete($id) {
    $msg = '';
    try {
        cruiseimages_delete($id);
        $msg = 'Gift Card Deleted Successfully.';
    } catch (Exception $e) {
        $msg = 'Operation Failed.';
    }
    drupal_set_message($msg);
    drupal_goto('admin/structure/cruiseimages/manage');
}

function cruiseimages_admin_page() {
//$output = 'Admin page for cruiseimages entities.<br/>';
    $output = '';
    $output .= '<a href="' . base_path() . 'cruiseimages/add">Add cruiseimages</a>';

    $output.=cruiseimages_list_view();

    return $output;
}

function cruiseimages_list_view() {
    $output = '';
    $header = array(
        array('data' => 'Id', 'field' => 'id'),
        array('data' => 'Card ID', 'field' => 'card_id'),
        array('data' => 'Status'),
        array('data' => 'Created'),
        array('data' => 'Actions'),
    );
    if (isset($_GET['sort']) && isset($_GET['order'])) {
        if ($_GET['sort'] == 'asc')
            $sort = 'ASC';
        else
            $sort = 'DESC';

        switch ($_GET['order']) {
            case 'Id':
                $order = 'id';
                break;
            case 'Card ID':
                $order = 'card_id';
                break;
        }
    } else {
        $sort = 'ASC';
        $order = 'id';
    }


    $query = db_select("cruiseimages", "n");
    $query->fields('n', array('id', 'card_id', 'created', 'flag'));
    $query->orderBy($order, $sort);
    $query = $query->extend('TableSort')->extend('PagerDefault')->limit(5);
    $result = $query->execute()->fetchAll();

    //var_dump($result[0]->card_id);
    //exit();

    global $base_url;
    $rows = array();
    if (count($result) > 0) {
        for ($i = 0; $i < count($result); $i++) {

            $createddate = $result[$i]->created != '' ? date('Y-m-d', $result[$i]->created) : "";
            // $d=$result[$i]->created!='' ? 
            $rows[] = array(
                $result[$i]->id,
                $result[$i]->card_id,
                $result[$i]->flag,
                $createddate,
                '<a href="' . $base_url . '/cruiseimages/' . $result[$i]->id . '/edit">Edit |</a>
                <a href="' . $base_url . '/cruiseimages/' . $result[$i]->id . '/delete">Delete</a>'
            );
        }
    }




//        while ($data = $result->fetchObject()) {
//            if (isset($data)) {
//                $rows[] = array(
//                    $data->id,
//                    $data->card_id,
//                    $data->flag,
//                    date('Y-m-d', $data->created),
//                    '<a href="' . $base_url . '/cruiseimages/' . $data->id . '/edit">Edit |</a>
//             <a href="' . $base_url . '/cruiseimages/' . $data->id . '/delete">Delete</a>'
//                );
//            }
//        }
//    






    $output .= '<div class="eventRecordsWrapper">';
    $output .= '<div class="cruiseEventSearchWrapper">';

    $output .= '</div>';
    $output .= theme_table(
                    array(
                        'header' => $header,
                        'rows' => $rows,
                        'attributes' => array('class' => array('')),
                        'sticky' => true,
                        'caption' => '',
                        'colgroups' => array(),
                        'empty' => t("No Records!"),
                    )
            ) . theme('pager');

    $output .= '</div>';

    return $output;
}

function cruiseimages_page_view($entity, $view_mode = 'tweaky') {

    // var_dump($entity);
    $entity_type = 'cruiseimages';
    $entity->content = array(
        '#view_mode' => $view_mode,
    );

    field_attach_prepare_view($entity_type, array($entity->id => $entity), $view_mode);
    entity_prepare_view($entity_type, array($entity->id => $entity));
    $entity->content += field_attach_view($entity_type, $entity, $view_mode);
    $entity->content['id'] = array(
        '#type' => 'item',
        '#title' => t('id'),
        '#markup' => $entity->id,
    );

    $entity->content['card_id'] = array(
        '#type' => 'item',
        '#title' => t('cardId'),
        '#value' => $entity->card_id,
    );
    global $language;
    $langcode = $language->language;
    module_invoke_all('entity_view', $entity, $entity_type, $view_mode, $langcode);
    drupal_alter(array('userdocuments_view', 'entity_view'), $entity->content, $entity_type);
    return $entity->content;
}

function cruiseimages_item_edit($cruiseimages) {
    drupal_set_title(t('<em>Edit Gift Card </em> @title', array('@title' =>
        '')), PASS_THROUGH);
    return drupal_get_form('cruiseimages_add_form', $cruiseimages);
}



function cruiseimages_field_extra_fields() {
    $form_elements['id'] = array(
        'label' => t('id'),
        'description' => t('Text'),
        'weight' => -5,
    );

    $form_elements['card_id'] = array(
        'label' => t('Card ID'),
        'description' => t('Text'),
        'weight' => -5,
    );

    $display_elements['id'] = array(
        'label' => t('id'),
        'description' => t('Text'),
        'weight' => -5,
    );

    $display_elements['card_id'] = array(
        'label' => t('card_id'),
        'description' => t('Text'),
        'weight' => -5,
    );


// Since we have only one bundle type, we'll just provide the extra_fields
// for it here.
    $extra_fields['cruiseimages']['cruiseimages_bundle']['form'] = $form_elements;
    $extra_fields['cruiseimages']['cruiseimages_bundle']['display'] = $display_elements;
    return $extra_fields;
}



function cruiseimages_save(&$cruiseimages) {
    return entity_get_controller('cruiseimages')->save($cruiseimages);
}

function cruiseimages_delete($id) {
    return entity_get_controller('cruiseimages')->delete($id);
}

function cruiseimages_status($card_id) {
    return cruiseimages_load_multiple($ids = array(), $conditions = array('card_id' => $card_id));
}

function cruiseimages_used_list() {
    return cruiseimages_load_multiple($ids = array(), $conditions = array('flag' => 1));
}

function cruiseimages_unused_list() {
    return cruiseimages_load_multiple($ids = array(), $conditions = array('flag' => 0));
}

